# Generated by Django 5.1.15 on 2026-02-08 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiId', models.IntegerField(unique=True, verbose_name='원본 ID')),
                ('title', models.CharField(max_length=200, verbose_name='영문 제목')),
                ('titleKo', models.CharField(blank=True, default='', max_length=200, verbose_name='한글 제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='영문 설명')),
                ('descriptionKo', models.TextField(blank=True, default='', verbose_name='한글 설명')),
                ('moduleType', models.CharField(max_length=20, verbose_name='타입(영문)')),
                ('moduleTypeKo', models.CharField(blank=True, default='', max_length=20, verbose_name='타입(한글)')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리(영문)')),
                ('categoryKo', models.CharField(blank=True, default='', max_length=50, verbose_name='카테고리(한글)')),
                ('operationsCount', models.IntegerField(default=0, verbose_name='Operations 수')),
                ('deprecatedCount', models.IntegerField(default=0, verbose_name='Deprecated 수')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='검색 키워드')),
                ('operations', models.JSONField(blank=True, default=list, verbose_name='Operation 목록')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API 모듈',
                'verbose_name_plural': 'API 모듈',
                'ordering': ['titleKo', 'title'],
                'indexes': [models.Index(fields=['category'], name='catalog_api_categor_6614f2_idx'), models.Index(fields=['moduleType'], name='catalog_api_moduleT_f5dc7f_idx'), models.Index(fields=['title', 'titleKo'], name='catalog_api_title_967374_idx')],
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP 메서드')),
                ('uri', models.CharField(max_length=500, verbose_name='URI 경로')),
                ('operationId', models.CharField(max_length=200, verbose_name='Operation ID')),
                ('deprecated', models.BooleanField(default=False, verbose_name='Deprecated 여부')),
                ('apiModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='catalog.apimodule', verbose_name='소속 API')),
            ],
            options={
                'verbose_name': '엔드포인트',
                'verbose_name_plural': '엔드포인트',
                'ordering': ['method', 'uri'],
                'indexes': [models.Index(fields=['method'], name='catalog_end_method_8ab250_idx'), models.Index(fields=['deprecated'], name='catalog_end_depreca_77b55d_idx'), models.Index(fields=['apiModule', 'method'], name='catalog_end_apiModu_2b3ffc_idx')],
            },
        ),
    ]
